# Generated by Django 3.2.6 on 2022-01-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0009_alter_client_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commentaire',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(max_length=12),
        ),
    ]
